[package]
name = "wasm-minisign-verify"
description = "The rust-minisign-verify crate compiled to WebAssembly."
version = "0.1.3"
authors = ["Danilo Bargen <danilo.bargen@ŧhreema.ch>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/threema-ch/wasm-minisign-verify"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "console_log", "wee_alloc"]

[dependencies]
cfg-if = "1.0.0"
minisign-verify = "0.2.0"
wasm-bindgen = { version = "=0.2.79", features = ["spans", "std"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.5", optional = true }

# Add logging support
log = "0.4"
console_log = { version = "0.2", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
